package networktests

import (
	"fmt"
	"tap/internal/network"
	"testing"
	"time"
)

func TestAcceptNewTCPConnection(t *testing.T) {
	in := make(chan network.IncomingEvent)
	out := make(chan network.OutgoingEvent)
	server, err := network.NewServer("127.0.0.1:0", in, out)
	if err != nil {
		fmt.Println("Server failed to start listening: ", err)
		return
	}
	server.Start()
	time.Sleep(10 * time.Millisecond)
	// for the ip:port generated by the OS on PORT :0 (random port given)
	realAdress := server.GetAddress()

}
