// protocol/commands.go
package protocol

const (
	CmdConnect              = "CONNECT"
	CmdLook                 = "LOOK"
	CmdMove                 = "MOVE"
	CmdChat                 = "CHAT"
	CmdTake                 = "TAKE"
	CmdDrop                 = "DROP"
	CmdInventory            = "INVENTORY"
	CmdUseItem              = "USE"
	CmdTalk                 = "TALK"
	CmdAttack               = "ATTACK"
	CmdFlee                 = "FLEE"
	CmdStatus               = "STATUS"
	CmdQuest                = "QUEST"
	CmdQuests               = "QUESTS"
	CmdCompleteQuest        = "COMPLETE_QUEST"
	CmdWho                  = "WHO"
	CmdUnGrouped            = "UNGROUPED"
	CmdGrouped              = "GROUPED"
	CmdGroup                = "GROUP"
	CmdCombat               = "COMBAT"
	CmdQuit                 = "QUIT"
	CmdInspect              = "INSPECT"
	CmdInspectPlayer        = "INSPECT PLAYER"
	CmdInspectNpc           = "INSPECT NPC"
	CmdInspectItem          = "INSPECT ITEM"
	CmdInspectInventoryItem = "INSPECT INVENTORY_ITEM"

	GlobalChat = "GLOBAL"
	RoomChat   = "ROOM"
	GroupChat  = "GROUP"
	CombatChat = "COMBAT"

	CreateGroup         = "CREATE"
	InviteGroup         = "INVITE"
	KickGroup           = "KICK"
	JoinGroup           = "JOIN"
	LeaveGroup          = "LEAVE"
	PromoteGroup        = "PROMOTE"
	AcceptPromoteGroup  = "ACCEPT"
	DeclinePromoteGroup = "DECLINE"

	CmdCreateGroup         = "GROUP CREATE"
	CmdInviteGroup         = "GROUP INVITE"
	CmdKickGroup           = "GROUP KICK"
	CmdJoinGroup           = "GROUP JOIN"
	CmdLeaveGroup          = "GROUP LEAVE"
	CmdPromoteGroup        = "GROUP PROMOTE"
	CmdAcceptPromoteGroup  = "GROUP ACCEPT"
	CmdDeclinePromoteGroup = "GROUP DECLINE"

	StatsCombat = "STATS"

	MsgOK                 = "OK"
	MsgErr                = "ERR"
	MsgEvt                = "EVT"
	PrefixOKGroup         = "OK group="
	PrefixOKPendingLeader = "OK pending_leader="
	PrefixOKNewLeader     = "OK new_leader="
	CmdChatCombat         = "CHAT COMBAT"
	CmdCombatStats        = "COMBAT STATS"
	CmdChatCombatAttack   = "CHAT COMBAT ATTACK"
	CmdChatCombatFlee     = "CHAT COMBAT FLEE"
	CombatActionAttack    = "ATTACK"
	CombatActionFlee      = "FLEE"

	EntityTypePlayer        = "PLAYER"
	EntityTypeNpc           = "NPC"
	EntityTypeItem          = "ITEM"
	EntityTypeInventoryItem = "INVENTORY_ITEM"
	EntityTypeRoom          = "ROOM"
	EntityTypeSelf          = "SELF"

	CmdInspectSelf = "INSPECT SELF"
)
